[tools]
odin = "dev-2026-07a"

[tasks.install]
run = "./bin/install"

[tasks.sync]
run = "./bin/sync"

[tasks.dev]
run = "./bin/dev"

[tasks.build]
run = "./bin/build"

[tasks.fmt]
run = "./bin/fmt"

[tasks.fmt-check]
run = "./bin/fmt-check"

[tasks.check]
run = "./bin/check"

[tasks.test-unit]
run = "./bin/test-unit"

[tasks.test-integration]
run = "./bin/test-integration"

[tasks.test]
run = "./bin/check"

[tasks.smoke]
run = "./bin/smoke"

[tasks.verify]
run = "./bin/verify"
